-- 212: unused arguments; 21/_.*: unused locals deliberately named with a _ prefix
ignore = {"212", "21/_.*"}
max_line_length = 160
max_comment_line_length = 500

-- Only lint the suite's own addons: the local AddOns dir also holds installed
-- third-party addons (untracked, see .gitignore), so an exclude list would
-- churn with every install. Add new suite addons here.
include_files = {
  "BarNonce/**/*.lua", "CombatOutline/**/*.lua", "HideBagBar/**/*.lua", "HideStanceBar/**/*.lua",
  "LibNAddOn/**/*.lua", "LibNUI/**/*.lua", "LibNUI_Test/**/*.lua", "Recycle/**/*.lua",
  "ShadowsOfUI-DMF/**/*.lua", "ShadowsOfUI-GCD/**/*.lua", "ShadowsOfUI-Known/**/*.lua", "ShadowsOfUI-XP/**/*.lua",
  "Warbandeer/**/*.lua", "Warbandeer_Alias/**/*.lua", "Warbandeer_Bars/**/*.lua",
  "Warbandeer_Characters/**/*.lua", "Warbandeer_Collected/**/*.lua",
}

-- CI installs the Lua toolchain into the workspace (leafo/gh-actions-lua and
-- -luarocks use .lua/.luarocks/.install); keep `luacheck .` off those trees.
exclude_files = {".lua", ".luarocks", ".install"}

files["**/spec/**/*.lua"] = {std = "+busted", read_globals = {"loadfile", "assert", "require", "tostring"}, globals = {"Mixin", "_G.Mixin"}}
-- Addons that intentionally define their own globals.
files["LibNUI/globals.lua"] = {globals = {"LibNUI"}, read_globals = {"LibNUITest"}}
files["LibNUI/debug.lua"] = {globals = {"SLASH_WDEBUG1"}}
files["LibNUI_Test/**/*.lua"] = {globals = {"LibNUITest"}}
files["ShadowsOfUI-DMF/**/*.lua"] = {globals = {"SLASH_SUI_DMF1"}}

std = {
  -- Globals the suite intentionally writes: dynamic global registration via
  -- _G (frames, APIs, slash commands) and SlashCmdList entries.
  globals = {
    "_G",
    "SlashCmdList",
  },
  read_globals = {
    "bit",
    "date",
    "floor",
    "format",
    "gsub",
    "ipairs",
    "loadstring",
    "math",
    "max",
    "next",
    "pairs",
    "pcall",
    "print",
    "setfenv",
    "setmetatable",
    "string",
    "strsplit",
    "strsub",
    "strtrim",
    "strupper",
    "table",
    "time",
    "tinsert",
    "tonumber",
    "tostring",
    "type",
    "unpack",
    "wipe",

    "CopyTable",
    "Mixin",
    "select",
    "tInvert",

    -- Globals defined by this suite's own addons (cross-addon reads).
    "LibNAddOn",
    "LibNUI",
    "WarbandeerBarsApi",

    "PrimaryResourceBar",
    "SecondaryResourceBar",

    "CopyToClipboard",
    "CreateColor",
    "CreateFont",
    "CreateFrame",
    "IsAddOnLoaded",
    "MinimalSliderWithSteppersMixin",
    "UiMapPoint",
    "hooksecurefunc",

    "C_AddOns",
    "C_AssistedCombat",
    "C_Bank",
    "C_Calendar",
    "C_ChatInfo",
    "C_ClassColor",
    "C_Container",
    "C_CurrencyInfo",
    "C_DateAndTime",
    "C_EquipmentSet",
    "C_GossipInfo",
    "C_Item",
    "C_KeyBindings",
    "C_MajorFactions",
    "C_Map",
    "C_MerchantFrame",
    "C_Minimap",
    "C_MountJournal",
    "C_PetJournal",
    "C_ProfSpecs",
    "C_QuestLog",
    "C_Reputation",
    "C_SpecializationInfo",
    "C_Spell",
    "C_SpellBook",
    "C_Timer",
    "C_TimerunningUI",
    "C_ToyBox",
    "C_TradeSkillUI",
    "C_Traits",
    "C_TransmogSets",
    "C_WeeklyRewards",
    "Enum",
    "Settings",

    "DARKYELLOW_FONT_COLOR",
    "DIM_GREEN_FONT_COLOR",
    "DIM_RED_FONT_COLOR",
    "DULL_RED_FONT_COLOR",
    "GREEN_FONT_COLOR",
    "ITEM_ARTIFACT_COLOR",
    "ITEM_EPIC_COLOR",
    "ITEM_GOOD_COLOR",
    "ITEM_LEGENDARY_COLOR",
    "ITEM_POOR_COLOR",
    "ITEM_QUALITY_COLORS",
    "ITEM_STANDARD_COLOR",
    "ITEM_SUPERIOR_COLOR",
    "NORMAL_FONT_COLOR",
    "PLAYER_FACTION_COLOR_ALLIANCE",
    "PLAYER_FACTION_COLOR_HORDE",
    "TRADESKILL_EXPERIENCE_COLOR",
    "WHITE_FONT_COLOR",
    "GameFontHighlightSmall",
    "NumberFontNormalSmallGray",

    "MAX_ACCOUNT_MACROS",
    "MAX_CHARACTER_MACROS",
    "NUM_BAG_SLOTS",
    "NUM_CHAT_WINDOWS",
    "NUM_PET_ACTION_SLOTS",

    "BagBarExpandToggle",
    "CalendarFrame",
    "CharacterBag0Slot",
    "CharacterBag1Slot",
    "CharacterBag2Slot",
    "CharacterBag3Slot",
    "CharacterReagentBag0Slot",
    "DEFAULT_CHAT_FRAME",
    "GameTooltip",
    "MainMenuBarBackpackButton",
    "StanceBar",
    "StatusTrackingBarManager",
    "UIParent",
    "UISpecialFrames",
    "WorldMapFrame",

    "BreakUpLargeNumbers",
    "BuyMerchantItem",
    "CastSpell",
    "ClearCursor",
    "CreateMacro",
    "FCF_OpenTemporaryWindow",
    "FindBaseSpellByID",
    "GetAchievementCriteriaInfo",
    "GetAchievementCriteriaInfoByID",
    "GetAchievementInfo",
    "GetActionInfo",
    "GetAverageItemLevel",
    "GetBinding",
    "GetBuildInfo",
    "GetCurrentBindingSet",
    "GetCursorInfo",
    "GetFactionInfoByID",
    "GetClassInfo",
    "GetFlyoutInfo",
    "GetFlyoutSlotInfo",
    "GetItemCooldown",
    "GetItemIcon",
    "GetItemInfo",
    "GetInventoryItemID",
    "GetLootSpecialization",
    "GetMacroInfo",
    "GetMaxLevelForPlayerExpansion",
    "GetMerchantItemID",
    "GetMerchantItemInfo",
    "GetMerchantItemMaxStack",
    "GetMerchantNumItems",
    "GetMoney",
    "GetNumBindings",
    "GetNumClasses",
    "GetNumMacros",
    "GetNumSavedInstances",
    "GetPetActionInfo",
    "GetProfessionInfo",
    "GetProfessions",
    "GetRealmName",
    "GetRestState",
    "GetSavedInstanceInfo",
    "GetServerExpansionLevel",
    "GetServerTime",
    "GetShapeshiftFormID",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GetSpecializationInfoByID",
    "GetSpecializationRoleByID",
    "GetTime",
    "GetXPExhaustion",
    "InCombatLockdown",
    "IsPetActive",
    "IsResting",
    "IsSpellKnown",
    "IsWindowsClient",
    "OpenAchievementFrameToAchievement",
    "PickupAction",
    "PickupMacro",
    "PickupPetAction",
    "PickupPetSpell",
    "PlaceAction",
    "PlayerHasToy",
    "PlayerIsTimerunning",
    "SaveBindings",
    "SetBinding",
    "SetCVar",
    "SetOverrideBindingClick",
    "ShowOptionsCategory",
    "UnitClass",
    "UnitClassBase",
    "UnitExists",
    "UnitGUID",
    "UnitHealth",
    "UnitHealthMax",
    "UnitIsAFK",
    "UnitLevel",
    "UnitName",
    "UnitPower",
    "UnitPowerMax",
    "UnitPowerType",
    "UnitRace",
    "UnitXP",
    "UnitXPMax",
    "UseToy"
  }
}
