-- 212: unused arguments; 21/_.*: unused locals deliberately named with a _ prefix
ignore = {"212", "21/_.*"}
max_line_length = 160
max_comment_line_length = 500

-- Only lint the suite's own addons: the local AddOns dir also holds installed
-- third-party addons (untracked, see .gitignore), so an exclude list would
-- churn with every install. Add new suite addons here.
include_files = {
  "BarNonce/**/*.lua", "CombatOutline/**/*.lua", "HideBagBar/**/*.lua", "HideStanceBar/**/*.lua",
  "LibNAddOn/**/*.lua", "LibNUI/**/*.lua", "LibNUI-ModelViewer/**/*.lua", "LibNUI_Test/**/*.lua",
  "MouselookToggle/**/*.lua",
  "Recycle/**/*.lua",
  "ShadowsOfUI-DMF/**/*.lua", "ShadowsOfUI-GCD/**/*.lua", "ShadowsOfUI-Ilvl/**/*.lua",
  "ShadowsOfUI-Known/**/*.lua", "ShadowsOfUI-Upgrade/**/*.lua", "ShadowsOfUI-XP/**/*.lua",
  "ShadowsOfUI-Artisan/**/*.lua", "ShadowsOfUI-WarbandInventory/**/*.lua",
  "ShadowsOfUI-Reputations/**/*.lua", "ShadowsOfUI-Quests/**/*.lua",
  "ShadowsOfUI-Compartment/**/*.lua", "ShadowsOfUI-Delves/**/*.lua",
  "ShadowsOfUI-Castbar/**/*.lua", "ShadowsOfUI-Collectibles/**/*.lua",
  "ShadowsOfUI-ProfCommissions/**/*.lua", "ShadowsOfUI-QuestXP/**/*.lua",
  "ShadowsOfUI-PostOffice/**/*.lua", "ShadowsOfUI-HousingVendor/**/*.lua",
  "Warbandeer/**/*.lua", "Warbandeer_Alias/**/*.lua", "Warbandeer_Bars/**/*.lua",
  "Warbandeer_Characters/**/*.lua", "Warbandeer_Collected/**/*.lua",
  "Warbandeer_HousingDecor/**/*.lua",
}

-- CI installs the Lua toolchain into the workspace (leafo/gh-actions-lua and
-- -luarocks use .lua/.luarocks/.install); keep `luacheck .` off those trees.
exclude_files = {".lua", ".luarocks", ".install"}

files["**/spec/**/*.lua"] = {std = "+busted", read_globals = {"loadfile", "assert", "require", "tostring"}, globals = {"Mixin", "_G.Mixin"}}
-- Addons that intentionally define their own globals.
files["LibNUI/globals.lua"] = {globals = {"LibNUI"}, read_globals = {"LibNUITest"}}
files["LibNUI/debug.lua"] = {globals = {"SLASH_WDEBUG1"}}
files["LibNUI_Test/**/*.lua"] = {globals = {"LibNUITest"}}
files["LibNAddOn/api.lua"] = {globals = {"LibNAddOn"}}
files["MouselookToggle/addon.lua"] = {globals = {"BINDING_NAME_MOUSELOOKTOGGLE_TOGGLE", "MouselookToggle_Toggle"}}
files["Recycle/addon.lua"] = {globals = {"HandleModifiedItemClick"}}
files["ShadowsOfUI-Artisan/**/*.lua"] = {globals = {"SLASH_SUI_ARTISAN1"}}
files["ShadowsOfUI-DMF/**/*.lua"] = {globals = {"SLASH_SUI_DMF1"}}
files["ShadowsOfUI-Ilvl/**/*.lua"] = {globals = {"SLASH_SUI_ILVL1"}}
files["ShadowsOfUI-Known/**/*.lua"] = {globals = {"SLASH_SUI_KNOWN1"}}
files["ShadowsOfUI-Upgrade/**/*.lua"] = {globals = {"SLASH_SUI_UPGRADE1", "ShadowsOfUI_UpgradeApi"}}
files["ShadowsOfUI-WarbandInventory/**/*.lua"] = {globals = {"SLASH_SUI_WINV1"}}
files["ShadowsOfUI-Reputations/**/*.lua"] = {globals = {"SLASH_SUI_REPS1"}}
files["ShadowsOfUI-Quests/**/*.lua"] = {globals = {"SLASH_SUI_QUESTS1"}}
files["ShadowsOfUI-Compartment/**/*.lua"] = {globals = {"SLASH_SUI_COMPARTMENT1"}}
files["ShadowsOfUI-Delves/**/*.lua"] = {globals = {"SLASH_SUI_DELVES1"}}
files["ShadowsOfUI-Castbar/**/*.lua"] = {globals = {"SLASH_SUI_CASTBAR1"}}
files["ShadowsOfUI-Collectibles/**/*.lua"] = {globals = {"SLASH_SUI_COLLECT1", "ShadowsOfUI_Collectibles_TintPreviewMixin"}}
files["ShadowsOfUI-HousingVendor/**/*.lua"] = {globals = {"SLASH_SUI_HVENDOR1"}}
files["ShadowsOfUI-ProfCommissions/**/*.lua"] = {globals = {"SLASH_SUI_PROFCOMM1", "ShadowsOfUI_ProfCommissions_InfoCellMixin"}}
files["ShadowsOfUI-QuestXP/**/*.lua"] = {globals = {"SLASH_SUI_QUESTXP1"}}
files["ShadowsOfUI-PostOffice/**/*.lua"] = {globals = {"SLASH_SUI_POSTOFFICE1", "InboxFrame", "InboxFrame_OnClick", "SendMailNameEditBox"}}
files["Warbandeer_Bars/init.lua"] = {globals = {"WarbandeerBarsSettings"}}

std = {
  -- Globals the suite intentionally writes: dynamic global registration via
  -- _G (frames, APIs, slash commands) and SlashCmdList entries.
  globals = {
    "_G",
    "SlashCmdList",
    "StaticPopupDialogs",
  },
  read_globals = {
    "bit",
    "canaccessvalue",
    "issecretvalue",
    "date",
    "floor",
    "format",
    "getmetatable",
    "gsub",
    "ipairs",
    "loadstring",
    "math",
    "max",
    "next",
    "pairs",
    "pcall",
    "print",
    "setfenv",
    "setmetatable",
    "string",
    "strfind",
    "strmatch",
    "strsplit",
    "strsub",
    "strtrim",
    "strupper",
    "table",
    "time",
    "tinsert",
    "tonumber",
    "tostring",
    "type",
    "unpack",
    "wipe",

    "AbbreviateNumbers",
    "CopyTable",
    "CreateFromMixins",
    "Mixin",
    "select",
    "TableBuilderCellMixin",
    "tInvert",

    -- Globals defined by this suite's own addons (cross-addon reads).
    "Baganator",
    "LibNAddOn",
    "LibNUI",
    "ShadowsOfUI_UpgradeApi",
    "WarbandeerApi",
    "WarbandeerBarsApi",
    "WarbandeerCollectedApi",
    "WarbandeerHousingDecorApi",
    "WarbandeerDB",

    "PrimaryResourceBar",
    "ReputationEntryMixin",
    "SecondaryResourceBar",

    "AreaPOIPinMixin",
    "DelveEntrancePinMixin",
    "CopyToClipboard",
    "CreateColor",
    "CreateFont",
    "DeltaLerp",
    "CreateFrame",
    "EventRegistry",
    "EventUtil",
    "GameTooltip_Hide",
    "Item",
    "GetCursorPosition",
    "GetCritChance",
    "GetHaste",
    "GetMasteryEffect",
    "GetCombatRating",
    "GetCombatRatingBonus",
    "CR_CRIT_MELEE",
    "CR_HASTE_MELEE",
    "CR_MASTERY",
    "CR_VERSATILITY_DAMAGE_DONE",
    "IsAddOnLoaded",
    "MinimalSliderWithSteppersMixin",
    "MouseIsOver",
    "TooltipDataProcessor",
    "TooltipUtil",
    "UiMapPoint",
    "CreateSettingsButtonInitializer",
    "EditModeManagerFrame",
    "FrameStackTooltip_Toggle",
    "ReloadUI",
    "ShowUIPanel",
    "hooksecurefunc",

    "C_AddOns",
    "C_AreaPoiInfo",
    "C_AssistedCombat",
    "C_AuctionHouse",
    "C_Bank",
    "C_Calendar",
    "C_ChallengeMode",
    "C_ChatInfo",
    "C_ClassColor",
    "C_Container",
    "C_CreatureInfo",
    "C_CurrencyInfo",
    "C_DateAndTime",
    "C_DelvesUI",
    "C_EditMode",
    "C_EquipmentSet",
    "C_GossipInfo",
    "C_GuildInfo",
    "C_Housing",
    "C_HousingCatalog",
    "C_Item",
    "C_KeyBindings",
    "C_MajorFactions",
    "C_Map",
    "C_MerchantFrame",
    "C_Minimap",
    "C_MountJournal",
    "C_MythicPlus",
    "C_NeighborhoodInitiative",
    "C_PaperDollInfo",
    "C_PartyInfo",
    "C_PerksActivities",
    "C_PerksProgram",
    "C_PetJournal",
    "C_PlayerInfo",
    "C_ProfSpecs",
    "C_QuestLog",
    "C_Reputation",
    "C_ScenarioInfo",
    "C_SpecializationInfo",
    "C_Spell",
    "C_SpellBook",
    "C_StableInfo",
    "C_SuperTrack",
    "C_TaskQuest",
    "C_Texture",
    "C_Timer",
    "C_TimerunningUI",
    "C_TooltipInfo",
    "C_ToyBox",
    "C_TradeSkillUI",
    "C_Traits",
    "C_TransmogCollection",
    "C_TransmogOutfitInfo",
    "C_TransmogSets",
    "C_UIWidgetManager",
    "C_WeeklyRewards",
    "Constants",
    "Enum",
    "ItemUtil",
    "Settings",

    "INVSLOT_MAINHAND",
    "INVSLOT_OFFHAND",
    "CAMERA_MODIFICATION_TYPE_DISCARD",
    "CAMERA_TRANSITION_TYPE_IMMEDIATE",
    "ORBIT_CAMERA_MOUSE_MODE_NOTHING",
    "ORBIT_CAMERA_MOUSE_MODE_ZOOM",
    "ORBIT_CAMERA_MOUSE_PAN_HORIZONTAL",
    "ORBIT_CAMERA_MOUSE_PAN_VERTICAL",
    "DARKYELLOW_FONT_COLOR",
    "DIM_GREEN_FONT_COLOR",
    "DIM_RED_FONT_COLOR",
    "DISABLED_FONT_COLOR",
    "GRAY_FONT_COLOR",
    "GREEN_FONT_COLOR",
    "HIGHLIGHT_FONT_COLOR",
    "HOUSING_DECOR_OWNED_COUNT_FORMAT",
    "ENCHANTED_TOOLTIP_LINE",
    "ITEM_ARTIFACT_COLOR",
    "ITEM_EPIC_COLOR",
    "ITEM_GOOD_COLOR",
    "ITEM_BIND_ON_PICKUP",
    "ITEM_LEVEL",
    "ITEM_MIN_SKILL",
    "ITEM_LEGENDARY_COLOR",
    "ITEM_POOR_COLOR",
    "ITEM_QUALITY_COLORS",
    "ITEM_SOULBOUND",
    "ITEM_STANDARD_COLOR",
    "ITEM_SUPERIOR_COLOR",
    "LARGE_NUMBER_SEPERATOR",
    "NO",
    "NORMAL_FONT_COLOR",
    "PLAYER_FACTION_COLOR_ALLIANCE",
    "PLAYER_FACTION_COLOR_HORDE",
    "RAID_CLASS_COLORS",
    "RED_FONT_COLOR",
    "RENOWN_LEVEL_LABEL",
    "TRADESKILL_EXPERIENCE_COLOR",
    "YES",
    "WHITE_FONT_COLOR",
    "GameFontHighlightSmall",
    "NumberFontNormalSmallGray",
    "ITEM_PET_KNOWN",
    "ITEM_SPELL_KNOWN",

    "ATTACHMENTS_MAX_RECEIVE",
    "MAX_ACCOUNT_MACROS",
    "MAX_CHARACTER_MACROS",
    "MAX_GUILDBANK_SLOTS_PER_TAB",
    "MERCHANT_ITEMS_PER_PAGE",
    "NUM_BAG_SLOTS",
    "NUM_CHAT_WINDOWS",
    "NUM_PET_ACTION_SLOTS",

    "AuctionHouseFrame",
    "BagBarExpandToggle",
    "BankPanel",
    "CalendarFrame",
    "ColorPickerFrame",
    "GuildBankFrame",
    "CharacterBag0Slot",
    "CharacterBag1Slot",
    "CharacterBag2Slot",
    "CharacterBag3Slot",
    "CharacterReagentBag0Slot",
    "DEFAULT_CHAT_FRAME",
    "GameTooltip",
    "MainMenuBarBackpackButton",
    "MapQuestInfoRewardsFrame",
    "ProfessionsBookFrame",
    "ProfessionsFrame",
    "ProfessionsCustomerOrdersFrame",
    "ProfessionsCrafterTableCellCommissionMixin",
    "ProfessionsSortOrder",
    "AddonCompartmentFrame",
    "Minimap",
    "GetMinimapShape",
    "MenuUtil",
    "SettingsPanel",
    "StanceBar",
    "StatusTrackingBarManager",
    "UIParent",
    "UISpecialFrames",
    "WorldMapFrame",

    "BreakUpLargeNumbers",
    "BuyMerchantItem",
    "CastSpell",
    "ChatFrame_AddMessageEventFilter",
    "ClearCursor",
    "ContainerFrameUtil_EnumerateContainerFrames",
    "CreateMacro",
    "FCF_OpenTemporaryWindow",
    "FindBaseSpellByID",
    "GetAchievementCriteriaInfo",
    "GetAchievementCriteriaInfoByID",
    "GetAchievementInfo",
    "GetActionInfo",
    "GetAverageItemLevel",
    "GetBinding",
    "GetBuildInfo",
    "GetClassInfo",
    "GetCurrentBindingSet",
    "GetCurrentGuildBankTab",
    "GetCursorInfo",
    "GetCVar",
    "GetExpansionLevel",
    "GetFactionInfoByID",
    "GetFlyoutInfo",
    "GetFlyoutSlotInfo",
    "GetGuildBankItemInfo",
    "GetGuildBankItemLink",
    "GetGuildBankTabInfo",
    "GetGuildInfo",
    "GetGuildRecipeInfoPostQuery",
    "GetGuildRecipeMember",
    "GetInboxHeaderInfo",
    "GetInboxItem",
    "GetInboxNumItems",
    "GetInstanceInfo",
    "GetInventoryItemID",
    "GetInventoryItemLink",
    "GetInventorySlotInfo",
    "GetItemCooldown",
    "GetItemIcon",
    "GetItemInfo",
    "GetLootSlotLink",
    "GetLootSpecialization",
    "GetMacroInfo",
    "GetMaxLevelForPlayerExpansion",
    "GetMerchantItemID",
    "GetMerchantItemLink",
    "ItemLocation",
    "GetMerchantItemInfo",
    "GetMerchantItemMaxStack",
    "GetMerchantNumItems",
    "ACCEPT",
    "ATTACHMENTS_MAX_SEND",
    "AMOUNT_PAID_COLON",
    "AMOUNT_RECEIVED_COLON",
    "AUCTION_HOUSE_CUT_COLON",
    "AUTOCOMPLETE_LIST",
    "AutoCompleteEditBox_SetAutoCompleteSource",
    "CANCEL",
    "DELETE",
    "DELETE_MAIL_CONFIRMATION",
    "DELETE_MONEY_CONFIRMATION",
    "DeleteInboxItem",
    "InboxItemCanDelete",
    "MAIL_RETURN",
    "MoneyFrame_Update",
    "BUYOUT",
    "C_AutoComplete",
    "C_FriendList",
    "ClickSendMailItemButton",
    "GetGuildRosterInfo",
    "GetNumGuildMembers",
    "IsInGuild",
    "CursorHasItem",
    "DEPOSIT_COLON",
    "FROM",
    "GetInboxInvoiceInfo",
    "GetInboxText",
    "GetSendMailItem",
    "HasSendMailItem",
    "GetCoinTextureString",
    "HIGH_BIDDER",
    "ITEM_PURCHASED_COLON",
    "ITEM_SOLD_COLON",
    "MAIL_SUBJECT_LABEL",
    "MailFrame",
    "MailFrameTab_OnClick",
    "OpenMailFrame",
    "OpenMailReplyButton",
    "OpenMailScrollFrame",
    "OpenMailSubject",
    "OpenMail_Update",
    "PURCHASED_BY_COLON",
    "SALE_PRICE_COLON",
    "SOLD_BY_COLON",
    "SendMailBodyEditBox",
    "TakeInboxItem",
    "TakeInboxMoney",
    "UNKNOWN",
    "GetMoney",
    "GetMouseButtonClicked",
    "InboxFrame_Update",
    "MoneyInputFrame_GetCopper",
    "MoneyInputFrame_SetOnValueChangedFunc",
    "ReturnInboxItem",
    "SendMailFrame",
    "SendMailFrame_SendMail",
    "SendMailMoney",
    "SendMailNameEditBox",
    "SendMailSubjectEditBox",
    "GetNumBindings",
    "GetNumClasses",
    "GetNumGuildBankTabs",
    "GetNumMacros",
    "GetNumQuestLogRewards",
    "GetNumSavedInstances",
    "GetNumSpecializationsForClassID",
    "GetPetActionInfo",
    "GetQuestLogItemLink",
    "GetQuestLogRewardInfo",
    "GetQuestLogRewardXP",
    "GetProfessionInfo",
    "GetProfessions",
    "GetRealmName",
    "GetRestState",
    "GetSavedInstanceInfo",
    "GetServerExpansionLevel",
    "GetServerTime",
    "GetShapeshiftFormID",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GetSpecializationMasterySpells",
    "GetSpecializationInfoByID",
    "GetSpecializationInfoForClassID",
    "GetSpecializationRoleByID",
    "GetTime",
    "GetCurrentTitle",
    "GetNumTitles",
    "GetTitleName",
    "GetXPExhaustion",
    "HandleModifiedItemClick",
    "HasNewMail",
    "HaveQuestRewardData",
    "InCombatLockdown",
    "IsAltKeyDown",
    "IsControlKeyDown",
    "IsPetActive",
    "IsResting",
    "IsMouseButtonDown",
    "IsMouselooking",
    "IsShiftKeyDown",
    "IsSpellKnown",
    "IsTitleKnown",
    "IsWindowsClient",
    "LibStub",
    "LoggingCombat",
    "MerchantFrame",
    "MouselookStart",
    "MouselookStop",
    "OpenAchievementFrameToAchievement",
    "ShowAchievementFrameForAchievement",
    "OpenAllBags",
    "PickupAction",
    "PickupMacro",
    "PickupMerchantItem",
    "PickupPetAction",
    "PickupPetSpell",
    "PlaceAction",
    "PlayerHasToy",
    "PlayerIsTimerunning",
    "QueryGuildBankTab",
    "QueryGuildRecipes",
    "RequestTimePlayed",
    "RunNextFrame",
    "SaveBindings",
    "SetBinding",
    "SetCurrentGuildBankTab",
    "SetCVar",
    "SetItemButtonDesaturated",
    "SetItemButtonNameFrameVertexColor",
    "SetItemButtonNormalTextureVertexColor",
    "SetItemButtonSlotVertexColor",
    "SetItemButtonTextureVertexColor",
    "SetOverrideBindingClick",
    "ShowOptionsCategory",
    "StaticPopup_Show",
    "UnitCastingInfo",
    "UnitChannelInfo",
    "UnitClass",
    "UnitClassBase",
    "UnitCreatureFamily",
    "UnitExists",
    "UnitGUID",
    "UnitHealth",
    "UnitHealthMax",
    "UnitIsAFK",
    "UnitLevel",
    "UnitName",
    "UnitPower",
    "UnitPowerMax",
    "UnitPowerType",
    "UnitRace",
    "UnitSex",
    "UnitXP",
    "UnitXPMax",
    "UseToy"
  }
}
