// Bare icon name -> a URL the webview can put in an <img src>.
//
// The bundle stores the identity WoW itself uses ("inv_misc_coin_01") rather than a path or a
// FileDataID, so it needs resolving before anything can draw it (nazumods/wow#842). The images
// are packed into the exe at generation time and served by src-tauri/src/icons.rs; this is the
// only place that knows the scheme's name.
import { convertFileSrc } from "@tauri-apps/api/core";
import manacrystal from "../assets/manacrystal.png";
import gold from "../assets/gold.jpg";

// Matches icons::SCHEME. Tauri rewrites it per platform — http://wbicon.localhost/<name> on
// Windows, wbicon://localhost/<name> elsewhere — which is exactly what convertFileSrc does, so
// the URL is never assembled by hand here.
const SCHEME = "wbicon";

// Hand-shipped stand-ins for the two names the packed set can never carry, mirroring the
// in-game addon, which ships its own TGAs for exactly this reason (Warbandeer/icons/*.tga).
// App assets rather than icons.bin entries on purpose: the blob is regenerated byte-for-byte
// from what the bundle references (update-static-data.ps1), so anything injected by hand
// would be dropped on the next weekly refresh — and presentation is the consumer's job.
const LOCAL: Record<string, string> = {
  // Untainted Mana-Crystals: DB2's icon name carries a literal space, and the CDN has no
  // image under any spelling of it (nazumods/wow#883) — converted from the addon's own TGA.
  "jewelcrafting_uncut epic gem_color1": manacrystal,
  // The Gold column's pseudo-name. Gold is GetMoney() copper, not a currency, so it has no
  // DB2 row to take an icon from; the prefix keeps it impossible to mistake for a real name.
  "wb:gold": gold,
};

/**
 * The image URL for a bare icon name, or null when there is nothing to draw.
 *
 * A large share of bundle rows carry `icon: null` (DB2 has no icon for most retired and
 * internal currencies), so null in means null out is the NORMAL case, not an error. A name
 * that resolves here can still 404 — a handful are referenced but have no image anywhere —
 * which the <img> consumer handles as the same "no icon" outcome.
 */
export function iconUrl(name: string | null | undefined): string | null {
  if (!name) return null;
  return LOCAL[name] ?? convertFileSrc(name, SCHEME);
}
